# Generated by Django 4.2.3 on 2023-08-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_familya_alter_user_img_alter_user_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Elektron pochtasi'),
        ),
    ]
