# Generated by Django 4.2.3 on 2023-08-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_is_spam_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='spam',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
