# Generated by Django 4.2.3 on 2023-08-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_spam_date_servicedocs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'DocServices', 'verbose_name_plural': '2.1 Narxlar'},
        ),
        migrations.AlterModelOptions(
            name='servicedocs',
            options={'verbose_name': 'Price', 'verbose_name_plural': '3. Doctor Sohalari'},
        ),
    ]
