# Generated by Django 4.2.3 on 2023-08-30 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_price_options_alter_servicedocs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedocs',
            name='doc',
            field=models.ForeignKey(limit_choices_to=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
